#include ./diagnostics.lex
#include ./symbols.lex
pl[ea]+se: please
o+w+: ow
phi+h: phee
u+h: uh
u+s: us
u+p: up
wo+w+: wow
ya+y+: yay
ti+red+: tired
thi+s+: this
tuu+li+: tuuli
freida: placeholder
#include ./exclamations.lex
